import { ComposeData, GlobalSettings, ServiceConfig } from '@/types';
import { getServiceSpecOrFallback } from '@/lib/catalog/spec-utils';
import { Document } from 'yaml';

const RESERVED_COMPOSE_KEYS = new Set([
  'image', 'build', 'container_name', 'restart', 'environment', 'ports', 'volumes',
  'devices', 'deploy', 'depends_on', 'labels', 'networks', 'configs', 'secrets',
  'healthcheck', 'command', 'entrypoint', 'working_dir', 'user', 'profiles',
  'platform', 'pull_policy',
]);

interface DiscoveredResources {
  networks: Set<string>;
  volumes: Set<string>;
  configs: Set<string>;
  secrets: Set<string>;
}

export function renderCompose(config: ComposeData, settings: GlobalSettings): string {
  const doc = new Document();
  doc.commentBefore = ' Generated by Compose Templater (compote)\n' +
                     ' Join our community: https://github.com/aicrafted/compote';

  const discovered: DiscoveredResources = {
    networks: new Set<string>(),
    volumes: new Set<string>(),
    configs: new Set<string>(),
    secrets: new Set<string>(),
  };

  const services: Record<string, unknown> = {};

  Object.entries(config.services).forEach(([id, svc]) => {
    const serviceDef = renderServiceDefinition(id, svc, config, settings, discovered);
    if (serviceDef) services[id] = serviceDef;
  });

  const composeObj: Record<string, unknown> = {};

  if (config.projectName) {
    composeObj.name = config.projectName;
  }

  const volumes = renderTopLevelVolumes(config);
  if (Object.keys(volumes).length > 0) {
    composeObj.volumes = volumes;
  }

  const networks = renderTopLevelNetworks(config, discovered.networks);
  if (Object.keys(networks).length > 0) {
    composeObj.networks = networks;
  }

  const configs = renderTopLevelConfigs(config, discovered.configs);
  if (Object.keys(configs).length > 0) {
    composeObj.configs = configs;
  }

  const secrets = renderTopLevelSecrets(config, discovered.secrets);
  if (Object.keys(secrets).length > 0) {
    composeObj.secrets = secrets;
  }

  composeObj.services = services;

  doc.contents = doc.createNode(composeObj);
  return formatEmptyTopLevelDeclarations(
    doc.toString(),
    Object.entries(networks).filter(([, value]) => value === null).map(([name]) => name)
  );
}

function formatEmptyTopLevelDeclarations(yaml: string, names: string[]): string {
  return names.reduce((output, name) => {
    const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return output.replace(new RegExp(`^(\\s{2}${escapedName}): null$`, 'gm'), '$1:');
  }, yaml);
}

function renderServiceDefinition(
  id: string,
  svc: ServiceConfig,
  config: ComposeData,
  settings: GlobalSettings,
  discovered: DiscoveredResources
): Record<string, unknown> | null {
  if (!svc.enabled) return null;

  const spec = getServiceSpecOrFallback(svc.serviceId, svc);
  const imageSplit = splitImageRef(svc.image || spec.image);
  const activeTag = svc.imageTag || imageSplit.tag || 'latest';

  const serviceDef: Record<string, unknown> = {
    image: `${imageSplit.base}:${activeTag}`,
    restart: svc.restart || settings.serviceRestartMode,
  };

  if (String(svc.containerName || '').trim()) {
    serviceDef.container_name = String(svc.containerName).trim();
  }

  if (svc.raw) {
    const safeRaw: Record<string, unknown> = {};
    Object.entries(svc.raw).forEach(([k, v]) => {
      if (!RESERVED_COMPOSE_KEYS.has(k)) safeRaw[k] = v;
    });
    Object.assign(serviceDef, safeRaw);
  }

  if (String(svc.command ?? '').trim()) serviceDef.command = String(svc.command).trim();
  if (String(svc.entrypoint ?? '').trim()) serviceDef.entrypoint = String(svc.entrypoint).trim();
  if (String(svc.workingDir ?? '').trim()) serviceDef.working_dir = String(svc.workingDir).trim();
  if (String(svc.user ?? '').trim()) serviceDef.user = String(svc.user).trim();
  if (svc.profiles?.length) serviceDef.profiles = svc.profiles;

  if (String(svc.platform ?? '').trim()) serviceDef.platform = String(svc.platform).trim();
  if (String(svc.pullPolicy ?? '').trim()) serviceDef.pull_policy = String(svc.pullPolicy).trim();

  const build = renderBuild(svc);
  if (build) serviceDef.build = build;

  const dependsOn = renderDependsOn(id, svc, config);
  if (dependsOn) serviceDef.depends_on = dependsOn;

  if (svc.env && Object.keys(svc.env).length > 0) {
    serviceDef.environment = svc.env;
  }

  if (svc.labels && Object.keys(svc.labels).length > 0) {
    serviceDef.labels = svc.labels;
  }

  const healthcheck = renderHealthcheck(svc);
  if (healthcheck) serviceDef.healthcheck = healthcheck;

  if (svc.ports && svc.ports.length > 0) {
    serviceDef.ports = svc.ports.map((p) => {
      let mapping = `${p.host}:${p.container}`;
      if (p.protocol && p.protocol !== 'tcp') {
        mapping += `/${p.protocol}`;
      }
      return mapping;
    });
  }

  if (svc.volumes && svc.volumes.length > 0) {
    const volumes = svc.volumes.map((v) => {
      if (!v.host || !v.container) return null;
      let entry = `${v.host}:${v.container}`;
      if (v.mode && v.mode !== 'rw') entry += `:${v.mode}`;

      if (v.type === 'volume') {
        discovered.volumes.add(v.host);
      }

      return entry;
    }).filter(Boolean);
    if (volumes.length > 0) serviceDef.volumes = volumes;
  }

  if (svc.devices && svc.devices.length > 0) {
    serviceDef.devices = svc.devices.map((device) => {
      if (!device.host || !device.container) return null;
      let entry = `${device.host}:${device.container}`;
      if (device.permissions) entry += `:${device.permissions}`;
      return entry;
    }).filter(Boolean);
  }

  const serviceNetworks = (svc.networks || []).map((network) => network.trim()).filter(Boolean);
  if (serviceNetworks.length > 0) {
    serviceDef.networks = serviceNetworks;
    serviceNetworks.forEach((network) => discovered.networks.add(network));
  }

  if (svc.configs && svc.configs.length > 0) {
    serviceDef.configs = svc.configs
      .filter((ref) => ref.source)
      .map((ref) => {
        discovered.configs.add(ref.source);
        if (!ref.target && !ref.mode) return ref.source;
        return {
          source: ref.source,
          ...(ref.target ? { target: ref.target } : {}),
          ...(ref.mode ? { mode: ref.mode } : {}),
        };
      });
  }

  if (svc.secrets && svc.secrets.length > 0) {
    serviceDef.secrets = svc.secrets
      .filter((ref) => ref.source)
      .map((ref) => {
        discovered.secrets.add(ref.source);
        if (!ref.target && !ref.mode) return ref.source;
        return {
          source: ref.source,
          ...(ref.target ? { target: ref.target } : {}),
          ...(ref.mode ? { mode: ref.mode } : {}),
        };
      });
  }

  const activeLimits = svc.limits || spec.resourceLimits;
  if (activeLimits && (String(activeLimits.cpus || '').trim() || String(activeLimits.memory || '').trim())) {
    const limits: Record<string, string> = {};
    if (String(activeLimits.cpus || '').trim()) limits.cpus = activeLimits.cpus || '';
    if (String(activeLimits.memory || '').trim()) limits.memory = activeLimits.memory || '';

    serviceDef.deploy = {
      ...(asRecord(serviceDef.deploy)),
      resources: {
        ...(asRecord(asRecord(serviceDef.deploy).resources)),
        limits,
      },
    };
  }

  return serviceDef;
}

function splitImageRef(image: string): { base: string; tag?: string } {
  const slashIndex = image.lastIndexOf('/');
  const colonIndex = image.lastIndexOf(':');
  if (colonIndex > slashIndex) {
    return { base: image.slice(0, colonIndex), tag: image.slice(colonIndex + 1) || undefined };
  }
  return { base: image };
}

function renderBuild(svc: ServiceConfig): Record<string, unknown> | null {
  if (!svc.build) return null;

  const build: Record<string, unknown> = {};
  if (String(svc.build.context ?? '').trim()) build.context = String(svc.build.context).trim();
  if (String(svc.build.dockerfile ?? '').trim()) build.dockerfile = String(svc.build.dockerfile).trim();
  if (String(svc.build.target ?? '').trim()) build.target = String(svc.build.target).trim();
  if (svc.build.args && Object.keys(svc.build.args).length > 0) build.args = svc.build.args;

  return Object.keys(build).length > 0 ? build : null;
}

function renderDependsOn(id: string, svc: ServiceConfig, config: ComposeData): Record<string, { condition: string }> | null {
  const spec = getServiceSpecOrFallback(svc.serviceId, svc);
  const catalogRequires = (spec.requires || []).map((service) => ({ service, condition: 'service_healthy' }));
  const userDepends = (svc.dependsOn || []).map((dependency) => (
    typeof dependency === 'string'
      ? { service: dependency, condition: 'service_healthy' }
      : dependency
  ));
  const allDepends = [...catalogRequires, ...userDepends]
    .filter((dependency) => config.services[dependency.service] !== undefined && dependency.service !== id);

  if (allDepends.length === 0) return null;

  return allDepends.reduce<Record<string, { condition: string }>>((acc, depId) => {
    acc[depId.service] = { condition: depId.condition };
    return acc;
  }, {});
}

function renderHealthcheck(svc: ServiceConfig): Record<string, unknown> | null {
  if (!svc.healthcheck) return null;

  if (svc.healthcheck.disable) {
    return { disable: true };
  }

  const healthcheck: Record<string, unknown> = {};
  if (String(svc.healthcheck.test || '').trim()) {
    healthcheck.test = ['CMD-SHELL', String(svc.healthcheck.test).trim()];
  }
  if (String(svc.healthcheck.interval || '').trim()) healthcheck.interval = svc.healthcheck.interval;
  if (String(svc.healthcheck.timeout || '').trim()) healthcheck.timeout = svc.healthcheck.timeout;
  if (Number.isFinite(svc.healthcheck.retries)) healthcheck.retries = svc.healthcheck.retries;
  if (String(svc.healthcheck.startPeriod || '').trim()) healthcheck.start_period = svc.healthcheck.startPeriod;

  return Object.keys(healthcheck).length > 0 ? healthcheck : null;
}

function renderTopLevelVolumes(config: ComposeData): Record<string, unknown> {
  const finalVolumes: Record<string, unknown> = {};
  Object.entries(config.volumes || {}).forEach(([name, def]) => {
    if (!def) return;
    const vDef: Record<string, unknown> = {};
    if (def.driver && def.driver !== 'local') vDef.driver = def.driver;
    if (def.external) vDef.external = true;
    if (def.name) vDef.name = def.name;
    if (Object.keys(vDef).length > 0) finalVolumes[name] = vDef;
  });
  return finalVolumes;
}

function renderTopLevelNetworks(config: ComposeData, discoveredNetworks: Set<string>): Record<string, unknown> {
  const finalNetworks: Record<string, unknown> = {};
  Object.entries(config.networks || {}).forEach(([name, def]) => {
    if (!def) return;
    const nDef: Record<string, unknown> = {};
    if (def.driver && def.driver !== 'bridge') nDef.driver = def.driver;
    if (def.external) nDef.external = true;
    if (def.internal) nDef.internal = true;
    if (def.attachable) nDef.attachable = true;
    if (def.name) nDef.name = def.name;
    if (def.labels) nDef.labels = def.labels;
    finalNetworks[name] = Object.keys(nDef).length > 0 ? nDef : null;
  });
  discoveredNetworks.forEach((network) => {
    if (!finalNetworks[network]) finalNetworks[network] = null;
  });
  return finalNetworks;
}

function renderTopLevelConfigs(config: ComposeData, discoveredConfigs: Set<string>): Record<string, unknown> {
  const finalConfigs: Record<string, unknown> = {};
  Object.entries(config.configs || {}).forEach(([name, def]) => {
    if (!def) return;
    const cDef: Record<string, unknown> = {};
    if (def.file && !def.external) cDef.file = def.file;
    if (def.external) cDef.external = true;
    if (def.name) cDef.name = def.name;
    finalConfigs[name] = cDef;
  });
  discoveredConfigs.forEach((configName) => {
    if (!finalConfigs[configName]) finalConfigs[configName] = {};
  });
  return finalConfigs;
}

function renderTopLevelSecrets(config: ComposeData, discoveredSecrets: Set<string>): Record<string, unknown> {
  const finalSecrets: Record<string, unknown> = {};
  Object.entries(config.secrets || {}).forEach(([name, def]) => {
    if (!def) return;
    const sDef: Record<string, unknown> = {};
    if (def.file && !def.external) sDef.file = def.file;
    if (def.external) sDef.external = true;
    if (def.name) sDef.name = def.name;
    finalSecrets[name] = sDef;
  });
  discoveredSecrets.forEach((secret) => {
    if (!finalSecrets[secret]) finalSecrets[secret] = {};
  });
  return finalSecrets;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? value as Record<string, unknown> : {};
}
