import { ComposeData, GlobalSettings } from '@/types';
import { renderCompose } from '../renderers/compose';
import { getCachedServiceSpec } from '@/lib/catalog/spec-utils';
import JSZip from 'jszip';

interface ExportManifest {
  files: { path: string; content: string }[];
}

export function generateExportManifest(config: ComposeData, settings: GlobalSettings): ExportManifest {
  const manifest: ExportManifest = { files: [] };

  // 1. compose.yml
  manifest.files.push({
    path: 'compose.yml',
    content: renderCompose(config, settings)
  });

  // 2. .env (optional but good practice)
  const envContent = `# Generated by compote\nCOMPOSE_PROJECT_NAME=stack\n`;
  manifest.files.push({
    path: '.env',
    content: envContent
  });

  // 3. Service specific config files
  Object.values(config.services).forEach(svc => {
    if (!svc.enabled) return;
    const spec = getCachedServiceSpec(svc.serviceId);
    if (spec?.configFiles) {
      spec.configFiles.forEach(file => {
        manifest.files.push({
          path: file.path,
          content: file.content
        });
      });
    }
  });

  return manifest;
}

export async function downloadComposeZip(config: ComposeData, settings: GlobalSettings) {
  const manifest = generateExportManifest(config, settings);
  const zip = new JSZip();

  manifest.files.forEach(file => {
    zip.file(file.path, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `stack-bundle.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function downloadHostZip(
  hostName: string,
  stacks: { name: string; data: ComposeData }[],
  settings: GlobalSettings
) {
  const zip = new JSZip();

  for (const stack of stacks) {
    const manifest = generateExportManifest(stack.data, settings);
    const folder = zip.folder(stack.name)!;
    manifest.files.forEach(file => folder.file(file.path, file.content));
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${hostName}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
